# Generated by Django 6.0.2 on 2026-02-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_category',
            field=models.CharField(choices=[('work', 'work'), ('personal', 'personal'), ('urgent', 'urgent')], default='work', max_length=100),
        ),
    ]
